# English translations for PACKAGE package.
# Copyright (C) 2014 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Automatically generated, 2014.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-04-07 14:22+0100\n"
"PO-Revision-Date: 2014-03-07 22:38+0000\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"Language: en_GB\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ASCII\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: CLI/main.py:57
msgid "CHOICE_QUESTION"
msgstr "Your choice? "

#: CLI/main.py:57
msgid "MAIN_MENU_TITLE"
msgstr "rRpg"

#: CLI/main.py:58
msgid "CHOICE_LOAD_GAME"
msgstr "Load an existing game"

#: CLI/main.py:58
msgid "CHOICE_NEW_GAME"
msgstr "Start a new game"

#: CLI/main.py:66
msgid "SAVED_GAME_MENU_TITLE"
msgstr "Choose a save game slot"

#: CLI/main.py:67
msgid "SAVED_GAME_CHOICE_QUESTION"
msgstr "Which slot? "

#: CLI/main.py:78
#, python-brace-format
msgid "OVERWRITE_SAVEDGAME_QUESTION_{choices}"
msgstr "Are you sure you want to overwrite this saved game? {choices} "

#: CLI/main.py:95
msgid "EMPTY_SAVED_GAME"
msgstr "Empty saved game"

#: CLI/main.py:100
#, python-brace-format
msgid "SAVED_GAME_INFO_{login}"
msgstr "{login}"

#: CLI/main.py:105
msgid "LOGIN_PROMPT"
msgstr "Login: "

#: CLI/main.py:108 core/commands/createPlayer.py:16
#: tests/core/commands/testCreatePlayer.py:46
#: tests/core/commands/testCreatePlayer.py:52
msgid "ERROR_SIGNUP_LOGIN_ALREADY_USED"
msgstr "This login is already used"

#: CLI/main.py:114
msgid "GENDER_PROMPT"
msgstr "Gender: "

#: CLI/main.py:114
msgid "GENDER_SELECTION"
msgstr "Gender selection"

#: CLI/main.py:127
msgid "SPECIES_PROMPT"
msgstr "Species: "

#: CLI/main.py:127
msgid "SPECIES_SELECTION"
msgstr "Species selection"

#: CLI/main.py:136
msgid "GAME_OVER_TEXT"
msgstr ""
"You have been defeated. Your name shall be remembered for ever.... Or not"

#: CLI/main.py:212
msgid "COMMAND_PROMPT"
msgstr "Command: "

#: CLI/main.py:231
msgid "ANSWER_NO"
msgstr "no"

#: CLI/main.py:231 CLI/main.py:236
msgid "ANSWER_YES"
msgstr "yes"

#: core/Rpg.py:37 tests/core/testRpg.py:22
msgid "ERROR_UNKNOWN_SELECTED_WORLD"
msgstr "Unknown selected world"

#: core/Rpg.py:49 tests/core/testRpg.py:29
msgid "ERROR_RRPG_INIT_INVALID_SAVED_GAME_ID"
msgstr "The chosen saved game does not exist"

#: core/Rpg.py:59 tests/core/testRpg.py:37
msgid "ERROR_SAVED_GAME_NEEDED_TO_INIT_PLAYER"
msgstr "A saved game is needed to initialise the player"

#: core/Rpg.py:70 tests/core/testRpg.py:47
msgid "ERROR_INVALID_FORMAT_ACTION"
msgstr "The action must be a list of strings"

#: core/command_factory.py:44 core/commands/help.py:38
#: tests/core/commands/testHelp.py:24 tests/core/commands/testHelp.py:79
#: tests/core/commands/testLook.py:11 tests/core/commands/testLook.py:37
#: tests/core/commands/testLook.py:54 tests/core/commands/testLook.py:59
#: tests/core/commands/testLook.py:64 tests/core/commands/testLook.py:73
#: tests/core/commands/testLook.py:78 tests/core/commands/testLook.py:83
#: tests/core/commands/testLook.py:88 tests/core/commands/testLook.py:96
#: tests/core/commands/testLook.py:101 tests/core/commands/testLook.py:106
#: tests/core/commands/testLook.py:111 tests/core/commands/testLook.py:117
#: tests/core/commands/testLook.py:122 tests/core/commands/testLook.py:130
#: tests/core/commands/testLook.py:135 tests/core/commands/testLook.py:140
#: tests/core/commands/testLook.py:149 tests/core/commands/testLook.py:158
#: tests/core/commands/testLook.py:167 tests/core/commands/testSave.py:49
#: tests/core/commands/testSave.py:66 tests/core/commands/testSave.py:85
#: tests/core/commands/testSave.py:104 tests/core/commands/testSave.py:191
#: tests/core/commands/testSave.py:203 tests/core/commands/testSave.py:223
#: tests/core/commands/testSave.py:226 tests/core/commands/testTake.py:147
msgid "LOOK_COMMAND"
msgstr "look"

#: core/command_factory.py:45 core/commands/help.py:22
#: tests/core/commands/testHelp.py:16 tests/core/commands/testHelp.py:63
#: tests/core/commands/testTalk.py:11 tests/core/commands/testTalk.py:16
#: tests/core/commands/testTalk.py:21 tests/core/commands/testTalk.py:26
#: tests/core/commands/testTalk.py:31 tests/core/commands/testTalk.py:36
#: tests/core/commands/testTalk.py:41 tests/core/commands/testTalk.py:46
#: tests/core/commands/testTalk.py:51
msgid "TALK_COMMAND"
msgstr "talk"

#: core/command_factory.py:46 core/commands/help.py:26
#: tests/core/commands/testAttack.py:25 tests/core/commands/testAttack.py:27
#: tests/core/commands/testAttack.py:31 tests/core/commands/testAttack.py:33
#: tests/core/commands/testEnter.py:21 tests/core/commands/testEnter.py:28
#: tests/core/commands/testHelp.py:18 tests/core/commands/testHelp.py:67
#: tests/core/commands/testLook.py:145 tests/core/commands/testLook.py:147
#: tests/core/commands/testLook.py:154 tests/core/commands/testLook.py:156
#: tests/core/commands/testLook.py:163 tests/core/commands/testLook.py:165
#: tests/core/commands/testMove.py:11 tests/core/commands/testMove.py:16
#: tests/core/commands/testMove.py:21 tests/core/commands/testMove.py:26
#: tests/core/commands/testMove.py:31 tests/core/commands/testMove.py:36
#: tests/core/commands/testMove.py:41 tests/core/commands/testMove.py:43
#: tests/core/commands/testMove.py:49 tests/core/commands/testMove.py:51
#: tests/core/commands/testMove.py:56 tests/core/commands/testMove.py:58
#: tests/core/commands/testMove.py:60 tests/core/commands/testMove.py:66
#: tests/core/commands/testMove.py:68 tests/core/commands/testMove.py:70
#: tests/core/commands/testMove.py:75 tests/core/commands/testMove.py:77
#: tests/core/commands/testMove.py:79 tests/core/commands/testMove.py:85
#: tests/core/commands/testMove.py:87 tests/core/commands/testMove.py:89
#: tests/core/commands/testMove.py:94 tests/core/commands/testMove.py:99
#: tests/core/commands/testSave.py:186 tests/core/commands/testSave.py:196
#: tests/core/commands/testSave.py:208 tests/core/commands/testSave.py:210
msgid "MOVE_COMMAND"
msgstr "move"

#: core/command_factory.py:47 core/commands/help.py:30
#: tests/core/commands/testEnter.py:11 tests/core/commands/testEnter.py:16
#: tests/core/commands/testEnter.py:23 tests/core/commands/testEnter.py:30
#: tests/core/commands/testEnter.py:35 tests/core/commands/testEnter.py:40
#: tests/core/commands/testEnter.py:45 tests/core/commands/testEnter.py:47
#: tests/core/commands/testEnter.py:52 tests/core/commands/testEnter.py:54
#: tests/core/commands/testEnter.py:59 tests/core/commands/testEnter.py:64
#: tests/core/commands/testEnter.py:69 tests/core/commands/testEnter.py:74
#: tests/core/commands/testExit.py:50 tests/core/commands/testExit.py:57
#: tests/core/commands/testHelp.py:20 tests/core/commands/testHelp.py:71
msgid "ENTER_COMMAND"
msgstr "enter"

#: core/command_factory.py:48 core/commands/help.py:34
#: tests/core/commands/testExit.py:10 tests/core/commands/testExit.py:15
#: tests/core/commands/testExit.py:20 tests/core/commands/testExit.py:25
#: tests/core/commands/testExit.py:30 tests/core/commands/testExit.py:35
#: tests/core/commands/testExit.py:40 tests/core/commands/testExit.py:45
#: tests/core/commands/testExit.py:52 tests/core/commands/testExit.py:59
#: tests/core/commands/testHelp.py:22 tests/core/commands/testHelp.py:75
msgid "EXIT_COMMAND"
msgstr "exit"

#: core/command_factory.py:49 core/commands/help.py:51
#: tests/core/commands/testDrop.py:48 tests/core/commands/testDrop.py:60
#: tests/core/commands/testDrop.py:114 tests/core/commands/testDrop.py:121
#: tests/core/commands/testDrop.py:128 tests/core/commands/testDrop.py:135
#: tests/core/commands/testDrop.py:143 tests/core/commands/testDrop.py:150
#: tests/core/commands/testDrop.py:157 tests/core/commands/testDrop.py:164
#: tests/core/commands/testDrop.py:171 tests/core/commands/testDrop.py:181
#: tests/core/commands/testDrop.py:192 tests/core/commands/testDrop.py:199
#: tests/core/commands/testDrop.py:206 tests/core/commands/testDrop.py:213
#: tests/core/commands/testDrop.py:220 tests/core/commands/testDrop.py:227
#: tests/core/commands/testDrop.py:234 tests/core/commands/testDrop.py:241
#: tests/core/commands/testDrop.py:248 tests/core/commands/testDrop.py:255
#: tests/core/commands/testDrop.py:262 tests/core/commands/testDrop.py:269
#: tests/core/commands/testHelp.py:31 tests/core/commands/testHelp.py:91
#: tests/core/commands/testInventory.py:21
#: tests/core/commands/testInventory.py:28 tests/core/commands/testSave.py:41
#: tests/core/commands/testSave.py:58 tests/core/commands/testSave.py:75
#: tests/core/commands/testSave.py:94 tests/core/commands/testSave.py:112
#: tests/core/commands/testSave.py:132 tests/core/commands/testSave.py:149
#: tests/core/commands/testSave.py:171 tests/core/commands/testSave.py:212
#: tests/core/commands/testTake.py:12 tests/core/commands/testTake.py:17
#: tests/core/commands/testTake.py:22 tests/core/commands/testTake.py:27
#: tests/core/commands/testTake.py:32 tests/core/commands/testTake.py:37
#: tests/core/commands/testTake.py:43 tests/core/commands/testTake.py:48
#: tests/core/commands/testTake.py:53 tests/core/commands/testTake.py:58
#: tests/core/commands/testTake.py:63 tests/core/commands/testTake.py:68
#: tests/core/commands/testTake.py:73 tests/core/commands/testTake.py:78
#: tests/core/commands/testTake.py:84 tests/core/commands/testTake.py:89
#: tests/core/commands/testTake.py:94 tests/core/commands/testTake.py:99
#: tests/core/commands/testTake.py:105 tests/core/commands/testTake.py:110
#: tests/core/commands/testTake.py:115 tests/core/commands/testTake.py:120
#: tests/core/commands/testTake.py:125 tests/core/commands/testTake.py:128
#: tests/core/commands/testTake.py:133 tests/core/commands/testTake.py:135
#: tests/core/commands/testTake.py:138 tests/core/commands/testTake.py:144
#: tests/core/commands/testTake.py:153 tests/core/commands/testTake.py:158
#: tests/core/commands/testTake.py:163 tests/core/commands/testTake.py:168
#: tests/core/commands/testTake.py:173 tests/core/commands/testTake.py:178
#: tests/core/commands/testTake.py:183 tests/core/commands/testTake.py:188
#: tests/core/commands/testTake.py:193 tests/core/commands/testTake.py:198
#: tests/core/commands/testTake.py:203
msgid "TAKE_COMMAND"
msgstr "take"

#: core/command_factory.py:50 core/commands/help.py:61
#: tests/core/commands/testDrop.py:14 tests/core/commands/testDrop.py:23
#: tests/core/commands/testDrop.py:32 tests/core/commands/testDrop.py:41
#: tests/core/commands/testDrop.py:53 tests/core/commands/testDrop.py:65
#: tests/core/commands/testDrop.py:73 tests/core/commands/testDrop.py:78
#: tests/core/commands/testDrop.py:83 tests/core/commands/testDrop.py:88
#: tests/core/commands/testDrop.py:93 tests/core/commands/testDrop.py:98
#: tests/core/commands/testDrop.py:103 tests/core/commands/testDrop.py:108
#: tests/core/commands/testDrop.py:116 tests/core/commands/testDrop.py:123
#: tests/core/commands/testDrop.py:130 tests/core/commands/testDrop.py:137
#: tests/core/commands/testDrop.py:145 tests/core/commands/testDrop.py:152
#: tests/core/commands/testDrop.py:159 tests/core/commands/testDrop.py:166
#: tests/core/commands/testDrop.py:173 tests/core/commands/testDrop.py:176
#: tests/core/commands/testDrop.py:183 tests/core/commands/testDrop.py:186
#: tests/core/commands/testDrop.py:194 tests/core/commands/testDrop.py:201
#: tests/core/commands/testDrop.py:208 tests/core/commands/testDrop.py:215
#: tests/core/commands/testDrop.py:222 tests/core/commands/testDrop.py:229
#: tests/core/commands/testDrop.py:236 tests/core/commands/testDrop.py:243
#: tests/core/commands/testDrop.py:250 tests/core/commands/testDrop.py:257
#: tests/core/commands/testDrop.py:264 tests/core/commands/testDrop.py:271
#: tests/core/commands/testHelp.py:39 tests/core/commands/testHelp.py:95
msgid "DROP_COMMAND"
msgstr "drop"

#: core/command_factory.py:51 core/commands/help.py:42
#: tests/core/commands/testHelp.py:26 tests/core/commands/testHelp.py:83
#: tests/core/commands/testInventory.py:11
#: tests/core/commands/testInventory.py:16
#: tests/core/commands/testInventory.py:23
#: tests/core/commands/testInventory.py:30 tests/core/commands/testSave.py:23
#: tests/core/commands/testSave.py:33 tests/core/commands/testSave.py:46
#: tests/core/commands/testSave.py:63 tests/core/commands/testSave.py:82
#: tests/core/commands/testSave.py:101 tests/core/commands/testSave.py:117
#: tests/core/commands/testSave.py:137 tests/core/commands/testSave.py:156
#: tests/core/commands/testSave.py:178 tests/core/commands/testSave.py:220
msgid "INVENTORY_COMMAND"
msgstr "inventory"

#: core/command_factory.py:52 core/commands/help.py:42
#: tests/core/commands/testHelp.py:26 tests/core/commands/testHelp.py:83
msgid "INVENTORY_SHORT_COMMAND"
msgstr "inv"

#: core/command_factory.py:53 core/commands/help.py:70
#: tests/core/commands/testHelp.py:46 tests/core/commands/testHelp.py:99
#: tests/core/commands/testStats.py:12 tests/core/commands/testStats.py:35
msgid "STATS_COMMAND"
msgstr "stats"

#: core/command_factory.py:54 core/commands/help.py:82
#: tests/core/commands/testHelp.py:13 tests/core/commands/testHelp.py:52
#: tests/core/commands/testHelp.py:59 tests/core/commands/testHelp.py:111
msgid "HELP_COMMAND"
msgstr "help"

#: core/command_factory.py:55 core/commands/help.py:46
#: tests/core/commands/testHelp.py:28 tests/core/commands/testHelp.py:87
#: tests/core/commands/testOpen.py:11 tests/core/commands/testOpen.py:16
#: tests/core/commands/testOpen.py:21 tests/core/commands/testOpen.py:26
#: tests/core/commands/testOpen.py:31 tests/core/commands/testOpen.py:36
#: tests/core/commands/testOpen.py:41 tests/core/commands/testOpen.py:46
#: tests/core/commands/testOpen.py:51 tests/core/commands/testOpen.py:60
#: tests/core/commands/testOpen.py:65 tests/core/commands/testOpen.py:69
#: tests/core/commands/testOpen.py:77 tests/core/commands/testOpen.py:81
#: tests/core/commands/testOpen.py:89 tests/core/commands/testOpen.py:98
#: tests/core/commands/testOpen.py:102 tests/core/commands/testOpen.py:106
#: tests/core/commands/testOpen.py:110 tests/core/commands/testOpen.py:114
#: tests/core/commands/testSave.py:120 tests/core/commands/testSave.py:140
#: tests/core/commands/testSave.py:159 tests/core/commands/testSave.py:181
msgid "OPEN_COMMAND"
msgstr "open"

#: core/command_factory.py:56 core/commands/help.py:78
#: tests/core/commands/testHelp.py:50 tests/core/commands/testHelp.py:107
#: tests/core/commands/testSave.py:18 tests/core/commands/testSave.py:28
#: tests/core/commands/testSave.py:77 tests/core/commands/testSave.py:96
#: tests/core/commands/testSave.py:151 tests/core/commands/testSave.py:173
#: tests/core/commands/testSave.py:198 tests/core/commands/testSave.py:214
msgid "SAVE_COMMAND"
msgstr "save"

#: core/command_factory.py:57 core/commands/help.py:74
#: tests/core/commands/testAttack.py:37 tests/core/commands/testAttack.py:42
#: tests/core/commands/testAttack.py:49 tests/core/commands/testAttack.py:62
#: tests/core/commands/testAttack.py:88 tests/core/commands/testAttack.py:101
#: tests/core/commands/testAttack.py:128 tests/core/commands/testAttack.py:144
#: tests/core/commands/testHelp.py:48 tests/core/commands/testHelp.py:103
msgid "ATTACK_COMMAND"
msgstr "attack"

#: core/command_factory.py:84 core/commands/help.py:86
#: tests/core/commands/testHelp.py:54 tests/core/commands/testHelp.py:115
#: tests/core/commands/testQuit.py:11 tests/core/commands/testQuit.py:16
msgid "QUIT_COMMAND"
msgstr "quit"

#: core/command_factory.py:84 core/commands/help.py:86
#: tests/core/commands/testHelp.py:54 tests/core/commands/testHelp.py:115
msgid "QUIT_SHORT_COMMAND"
msgstr "q"

#: core/command_factory.py:91
msgid "ERROR_DENIED_COMMAND_WHILE_FIGHTING"
msgstr "You can't use this command while fighting"

#: core/command_factory.py:98 core/command_factory.py:112
#: tests/core/testRpg.py:52 tests/core/testRpg.py:57
msgid "ERROR_UNKNOWN_COMMAND"
msgstr "Unknown command"

#: core/commands/attack.py:19 tests/core/commands/testAttack.py:39
#: tests/core/commands/testAttack.py:44
msgid "ERROR_FIGHT_NOT_FIGHTING"
msgstr "You are not fighting"

#: core/commands/attack.py:30 tests/core/commands/testAttack.py:54
#: tests/core/commands/testAttack.py:93 tests/core/commands/testAttack.py:135
#, python-brace-format
msgid "ATTACK_CONFIRM_PLAYER_TO_ENEMY_{enemy}_{damages}"
msgstr "You attack the {enemy} and deal {damages} damage points"

#: core/commands/attack.py:31 core/commands/move.py:74
#: tests/core/commands/testAttack.py:55 tests/core/commands/testAttack.py:136
#, python-brace-format
msgid "ATTACK_CONFIRM_ENEMY_TO_PLAYER_{enemy}_{damages}"
msgstr "The {enemy} attacks you reducing your health of {damages} points"

#: core/commands/attack.py:32 tests/core/commands/testAttack.py:94
#, python-brace-format
msgid "ATTACK_VICTORY_{enemy}"
msgstr "You slay the {enemy}"

#: core/commands/attack.py:33 tests/core/commands/testAttack.py:137
#, python-brace-format
msgid "ATTACK_LOST_{enemy}"
msgstr "The {enemy} kills you"

#: core/commands/authenticate.py:17 tests/core/commands/testAuthenticate.py:15
#: tests/core/commands/testAuthenticate.py:20
msgid "ERROR_AUTHENTICATE_ARGUMENTS_NUMBER"
msgstr "One argument is required (Login)"

#: core/commands/authenticate.py:26 tests/core/commands/testAuthenticate.py:35
msgid "PLAYER_AUTHENTICATION_CONFIRMATION"
msgstr "Player connected"

#: core/commands/createPlayer.py:10 tests/core/commands/testCreatePlayer.py:34
#: tests/core/commands/testCreatePlayer.py:40
msgid "ERROR_SIGNUP_NOT_ENOUGH_ARGUMENTS"
msgstr "More arguments are required to create a player"

#: core/commands/createPlayer.py:20 tests/core/commands/testCreatePlayer.py:58
#: tests/core/commands/testCreatePlayer.py:64
msgid "ERROR_SIGNUP_INVALID_GENDER"
msgstr "Invalid gender"

#: core/commands/createPlayer.py:24 tests/core/commands/testCreatePlayer.py:70
#: tests/core/commands/testCreatePlayer.py:76
msgid "ERROR_SIGNUP_INVALID_SPECIES"
msgstr "Invalid species"

#: core/commands/createPlayer.py:43 tests/core/commands/testCreatePlayer.py:82
msgid "PLAYER_CREATION_CONFIRMATION"
msgstr "Player created"

#: core/commands/drop.py:20 tests/core/commands/testDrop.py:75
#: tests/core/commands/testDrop.py:80 tests/core/commands/testDrop.py:85
#: tests/core/commands/testDrop.py:90
msgid "ERROR_DROP_NO_ITEM_GIVEN"
msgstr "What shall I drop?"

#: core/commands/drop.py:22 tests/core/commands/testDrop.py:34
#: tests/core/commands/testDrop.py:43
msgid "ERROR_DROP_TOO_LOW_QUANTITY"
msgstr "You must drop at least one item."

#: core/commands/drop.py:24 tests/core/commands/testDrop.py:16
#: tests/core/commands/testDrop.py:25
msgid "ERROR_DROP_INVALID_FORMAT_QUANTITY"
msgstr "The quantity of items to drop must be a natural number."

#: core/commands/drop.py:26 tests/core/commands/testDrop.py:161
#: tests/core/commands/testDrop.py:168
msgid "ERROR_DROP_INVALID_CONTAINER_INDEX"
msgstr "The provided container index is not valid. Natural number expected."

#: core/commands/drop.py:40 tests/core/commands/testDrop.py:95
#: tests/core/commands/testDrop.py:100
msgid "ERROR_DROP_UNKNOWN_ITEM"
msgstr "I have none of those"

#: core/commands/drop.py:45 tests/core/commands/testDrop.py:105
#: tests/core/commands/testDrop.py:110
msgid "ERROR_DROP_ITEM_NOT_AVAILABLE"
msgstr "I have none of those"

#: core/commands/drop.py:47 tests/core/commands/testDrop.py:55
#: tests/core/commands/testDrop.py:67
#, python-format
msgid "ERROR_DROP_QUANTITY_TOO_HIGH_%s"
msgstr "I don't have enough %s to drop"

#: core/commands/drop.py:62 tests/core/commands/testDrop.py:196
#: tests/core/commands/testDrop.py:210 tests/core/commands/testDrop.py:224
#: tests/core/commands/testDrop.py:238 tests/core/commands/testDrop.py:252
#: tests/core/commands/testDrop.py:266
#, python-format
msgid "DROP_CONFIRMATION_%(quantity)s_%(name)s"
msgstr "You drop %(quantity)s %(name)s"

#: core/commands/enter.py:21 tests/core/commands/testEnter.py:13
#: tests/core/commands/testEnter.py:18
msgid "ERROR_ENTER_NO_PLACE_GIVEN"
msgstr "I can't enter into nothing"

#: core/commands/enter.py:27 core/commands/exit.py:27
#: tests/core/commands/testEnter.py:25 tests/core/commands/testEnter.py:32
#: tests/core/commands/testEnter.py:49 tests/core/commands/testEnter.py:56
#: tests/core/commands/testExit.py:22 tests/core/commands/testExit.py:27
#: tests/core/commands/testExit.py:42 tests/core/commands/testExit.py:47
msgid "ERROR_ENTER_PLACE_NOT_AVAILABLE"
msgstr "There is no such place here"

#: core/commands/enter.py:32 tests/core/commands/testEnter.py:61
#: tests/core/commands/testEnter.py:66 tests/core/commands/testEnter.py:71
#: tests/core/commands/testEnter.py:76
msgid "ENTER_CONFIRMATION"
msgstr "You enter."

#: core/commands/exit.py:21 tests/core/commands/testExit.py:12
#: tests/core/commands/testExit.py:17
msgid "ERROR_EXIT_NO_PLACE_GIVEN"
msgstr "I can't exit out of nothing"

#: core/commands/exit.py:30 tests/core/commands/testExit.py:54
#: tests/core/commands/testExit.py:61
msgid "EXIT_CONFIRMATION"
msgstr "You are now outside"

#: core/commands/help.py:22 tests/core/commands/testHelp.py:16
#: tests/core/commands/testHelp.py:63
msgid "CHARACTER_TOKEN"
msgstr "character name"

#: core/commands/help.py:22 tests/core/commands/testHelp.py:16
#: tests/core/commands/testHelp.py:63
msgid "SENTENCE_TOKEN"
msgstr "sentence"

#: core/commands/help.py:23 tests/core/commands/testHelp.py:17
#: tests/core/commands/testHelp.py:64
msgid "TALK_COMMAND_DESCRIPTION"
msgstr "Talk to a character"

#: core/commands/help.py:27 tests/core/commands/testHelp.py:19
#: tests/core/commands/testHelp.py:68
msgid "MOVE_COMMAND_DESCRIPTION"
msgstr "Go to the indicated direction"

#: core/commands/help.py:31 tests/core/commands/testHelp.py:21
#: tests/core/commands/testHelp.py:72
msgid "ENTER_COMMAND_DESCRIPTION"
msgstr ""
"Enter in the selected place (if the place is available in the current cell)"

#: core/commands/help.py:35 tests/core/commands/testHelp.py:23
#: tests/core/commands/testHelp.py:76
msgid "EXIT_COMMAND_DESCRIPTION"
msgstr "Exit from the selected place (if the current cell is the place exit)"

#: core/commands/help.py:39 tests/core/commands/testHelp.py:25
#: tests/core/commands/testHelp.py:80
msgid "LOOK_COMMAND_DESCRIPTION"
msgstr ""
"List everything which is in the current area (characters, items, neighbour "
"areas...)"

#: core/commands/help.py:43 tests/core/commands/testHelp.py:27
#: tests/core/commands/testHelp.py:84
msgid "INVENTORY_COMMAND_DESCRIPTION"
msgstr "List the items the player has in his inventory"

#: core/commands/help.py:46 core/commands/help.py:55 core/commands/help.py:65
#: tests/core/commands/testHelp.py:28 tests/core/commands/testHelp.py:35
#: tests/core/commands/testHelp.py:43 tests/core/commands/testHelp.py:87
#: tests/core/commands/testHelp.py:91 tests/core/commands/testHelp.py:95
msgid "CONTAINER_INDEX_TOKEN"
msgstr "container index"

#: core/commands/help.py:46 core/commands/help.py:54 core/commands/help.py:64
#: tests/core/commands/testHelp.py:28 tests/core/commands/testHelp.py:34
#: tests/core/commands/testHelp.py:42 tests/core/commands/testHelp.py:87
#: tests/core/commands/testHelp.py:91 tests/core/commands/testHelp.py:95
msgid "CONTAINER_TOKEN"
msgstr "container"

#: core/commands/help.py:47 tests/core/commands/testHelp.py:29
#: tests/core/commands/testHelp.py:88
msgid "OPEN_COMMAND_DESCRIPTION"
msgstr "List the items available in a given container"

#: core/commands/help.py:52 core/commands/help.py:62
#: tests/core/commands/testHelp.py:32 tests/core/commands/testHelp.py:40
#: tests/core/commands/testHelp.py:91 tests/core/commands/testHelp.py:95
msgid "QUANTITY_TOKEN"
msgstr "quantity"

#: core/commands/help.py:53 core/commands/help.py:63
#: tests/core/commands/testHelp.py:33 tests/core/commands/testHelp.py:41
#: tests/core/commands/testHelp.py:91 tests/core/commands/testHelp.py:95
msgid "ITEM_NAME_TOKEN"
msgstr "item name"

#: core/commands/help.py:57 tests/core/commands/testHelp.py:37
#: tests/core/commands/testHelp.py:92
msgid "TAKE_COMMAND_DESCRIPTION"
msgstr "Take some items on the ground"

#: core/commands/help.py:67 tests/core/commands/testHelp.py:45
#: tests/core/commands/testHelp.py:96
msgid "DROP_COMMAND_DESCRIPTION"
msgstr "Drop some items from your inventory"

#: core/commands/help.py:71 tests/core/commands/testHelp.py:47
#: tests/core/commands/testHelp.py:100
msgid "STATS_COMMAND_DESCRIPTION"
msgstr "Shows your character's stats"

#: core/commands/help.py:75 tests/core/commands/testHelp.py:49
#: tests/core/commands/testHelp.py:104
msgid "ATTACK_COMMAND_DESCRIPTION"
msgstr ""
"If the character is fighting, this command makes the character attack\n"
"If the character is not fighting, the command will fail and return an error"

#: core/commands/help.py:79 tests/core/commands/testHelp.py:51
#: tests/core/commands/testHelp.py:108
msgid "SAVE_COMMAND_DESCRIPTION"
msgstr "Save the game progress"

#: core/commands/help.py:83 tests/core/commands/testHelp.py:53
#: tests/core/commands/testHelp.py:112
msgid "HELP_COMMAND_DESCRIPTION"
msgstr "Display the help menu"

#: core/commands/help.py:87 tests/core/commands/testHelp.py:55
#: tests/core/commands/testHelp.py:116
msgid "QUIT_COMMAND_DESCRIPTION"
msgstr "Quit the game"

#: core/commands/help.py:92 tests/core/commands/testHelp.py:15
msgid "AVAILABLE_COMMANDS_TITLE"
msgstr "Available commands"

#: core/commands/inventory.py:27 tests/core/commands/testInventory.py:13
#: tests/core/commands/testSave.py:25 tests/core/commands/testSave.py:48
#: tests/core/commands/testSave.py:119
msgid "INVENTORY_EMPTY"
msgstr "Your inventory is empty"

#: core/commands/item_interaction.py:50 tests/core/commands/testDrop.py:132
#: tests/core/commands/testDrop.py:139 tests/core/commands/testOpen.py:23
#: tests/core/commands/testOpen.py:28 tests/core/commands/testTake.py:96
#: tests/core/commands/testTake.py:101
msgid "ERROR_CONTAINER_NOT_AVAILABLE"
msgstr "There is no container with this type here"

#: core/commands/item_interaction.py:56 tests/core/commands/testDrop.py:175
#: tests/core/commands/testDrop.py:178 tests/core/commands/testDrop.py:185
#: tests/core/commands/testDrop.py:188 tests/core/commands/testOpen.py:67
#: tests/core/commands/testOpen.py:79 tests/core/commands/testOpen.py:100
#: tests/core/commands/testOpen.py:108 tests/core/commands/testTake.py:127
#: tests/core/commands/testTake.py:130 tests/core/commands/testTake.py:137
#: tests/core/commands/testTake.py:140
#, python-format
msgid "ERROR_OUT_OF_RANGE_ITEM_CONTAINER_INDEX_%d"
msgstr ""
"The provided container index is not valid. A natural number between 1 and %d "
"is expected."

#: core/commands/item_interaction.py:59 tests/core/commands/testDrop.py:147
#: tests/core/commands/testDrop.py:154 tests/core/commands/testOpen.py:43
#: tests/core/commands/testOpen.py:48 tests/core/commands/testTake.py:107
#: tests/core/commands/testTake.py:112
msgid "ERROR_MULTIPLE_CONTAINERS_AVAILABLE"
msgstr ""
"There are more than one container with this type here, an explicit index is "
"required"

#: core/commands/look.py:20 tests/core/commands/testLook.py:64
#: tests/core/commands/testLook.py:73 tests/core/commands/testLook.py:167
#: tests/core/commands/testSave.py:191 tests/core/commands/testSave.py:203
#: tests/core/commands/testSave.py:226
msgid "LOOK_REGION_PARAM"
msgstr "region"

#: core/commands/look.py:21 tests/core/commands/testLook.py:135
#: tests/core/commands/testLook.py:140 tests/core/commands/testLook.py:149
#: tests/core/commands/testLook.py:158
msgid "LOOK_FIGHT_PARAM"
msgstr "enemies"

#: core/commands/look.py:22 tests/core/commands/testLook.py:78
#: tests/core/commands/testLook.py:83
msgid "LOOK_CHARACTERS_PARAM"
msgstr "characters"

#: core/commands/look.py:23 tests/core/commands/testLook.py:88
#: tests/core/commands/testLook.py:96
msgid "LOOK_DIRECTIONS_PARAM"
msgstr "diections"

#: core/commands/look.py:24 tests/core/commands/testLook.py:101
#: tests/core/commands/testLook.py:106
msgid "LOOK_PLACES_PARAM"
msgstr "places"

#: core/commands/look.py:25 tests/core/commands/testLook.py:111
#: tests/core/commands/testLook.py:117 tests/core/commands/testSave.py:49
#: tests/core/commands/testSave.py:66 tests/core/commands/testSave.py:85
#: tests/core/commands/testSave.py:104 tests/core/commands/testSave.py:223
#: tests/core/commands/testTake.py:147
msgid "LOOK_OBJECTS_PARAM"
msgstr "objects"

#: core/commands/look.py:26 tests/core/commands/testLook.py:122
#: tests/core/commands/testLook.py:130
msgid "LOOK_CONTAINERS_PARAM"
msgstr "containers"

#: core/commands/look.py:38 tests/core/commands/testLook.py:56
#: tests/core/commands/testLook.py:61
msgid "ERROR_LOOK_UNKNOWN_SECTION"
msgstr "Unknown option for the look command"

#: core/commands/look.py:114 tests/core/commands/testLook.py:14
#: tests/core/commands/testLook.py:67
#, python-format
msgid "CURRENT_REGION_%s"
msgstr "You are in %s"

#: core/commands/look.py:117 tests/core/commands/testLook.py:15
#: tests/core/commands/testLook.py:68
msgid "AREA_HAS_SAVE_POINT"
msgstr "You can save your progress here"

#: core/commands/look.py:121 tests/core/commands/testLook.py:151
#, python-format
msgid "CURRENTLY_FIGHTING_%s"
msgstr "You are currently fighting: %s"

#: core/commands/look.py:125 tests/core/commands/testLook.py:17
#: tests/core/commands/testLook.py:80
msgid "PRESENT_CHARACTERS"
msgstr "You see these characters arround:"

#: core/commands/look.py:132 tests/core/commands/testLook.py:20
#: tests/core/commands/testLook.py:91
msgid "AVAILABLE_DIRECTIONS"
msgstr "You can go in the following directions:"

#: core/commands/look.py:139 tests/core/commands/testLook.py:23
#: tests/core/commands/testLook.py:103
msgid "AVAILABLE_PLACES"
msgstr "You see the following places:"

#: core/commands/look.py:146 tests/core/commands/testLook.py:27
#: tests/core/commands/testLook.py:113 tests/core/commands/testSave.py:51
#: tests/core/commands/testSave.py:87 tests/core/commands/testTake.py:149
msgid "AVAILABLE_ITEMS"
msgstr "You see the following items"

#: core/commands/look.py:153 tests/core/commands/testLook.py:30
#: tests/core/commands/testLook.py:124
msgid "AVAILABLE_ITEMS_CONTAINERS"
msgstr "Available containers"

#: core/commands/move.py:21 tests/core/commands/testMove.py:13
#: tests/core/commands/testMove.py:18
msgid "ERROR_MOVE_NO_DIRECTION_GIVEN"
msgstr "Where shall I go?"

#: core/commands/move.py:25 tests/core/commands/testMove.py:23
#: tests/core/commands/testMove.py:28
#, python-format
msgid "ERROR_MOVE_INVALID_DIRECTION_%s"
msgstr "%s is not a valid direction"

#: core/commands/move.py:32 tests/core/commands/testMove.py:33
#: tests/core/commands/testMove.py:38
msgid "ERROR_MOVE_DIRECTION_NOT_AVAILABLE"
msgstr "I can't go there"

#: core/commands/move.py:41 tests/core/commands/testMove.py:82
#: tests/core/commands/testMove.py:91
msgid "ERROR_FLEE_FIGHT_FAILS"
msgstr "You can't run away from this fight"

#: core/commands/move.py:71 tests/core/commands/testMove.py:63
#, python-brace-format
msgid "MOVE_CONFIRMATION_{direction}_FIGHT_FLEE_{enemy}"
msgstr "You manage to escape the {enemy} and head towards {direction}"

#: core/commands/move.py:72 tests/core/commands/testMove.py:46
#, python-brace-format
msgid "MOVE_CONFIRMATION_{direction}_FIGHT_{enemy}"
msgstr "let's go {direction}. A {enemy} attacks you"

#: core/commands/move.py:73
#, python-brace-format
msgid "MOVE_CONFIRMATION_{direction}_AMBUSH_{enemy}"
msgstr "let's go {direction}. You are ambushed by a {enemy}"

#: core/commands/move.py:90 tests/core/commands/testMove.py:96
#, python-format
msgid "MOVE_CONFIRMATION_%s"
msgstr "let's go %s"

#: core/commands/open.py:18 tests/core/commands/testOpen.py:13
#: tests/core/commands/testOpen.py:18
msgid "ERROR_OPEN_NO_CONTAINER_PROVIDED"
msgstr "A container type must be provided"

#: core/commands/open.py:44 tests/core/commands/testOpen.py:54
#: tests/core/commands/testOpen.py:72 tests/core/commands/testOpen.py:84
#: tests/core/commands/testOpen.py:92 tests/core/commands/testSave.py:123
#: tests/core/commands/testSave.py:162
#, python-format
msgid "ITEMS_IN_CONTAINER_%s"
msgstr "Items in container %s"

#: core/commands/save.py:25 tests/core/commands/testSave.py:216
msgid "ERROR_SAVE_NO_SAVE_POINT"
msgstr "There is no save point here"

#: core/commands/save.py:36
msgid "SAVE_CONFIRMATION_OK"
msgstr "Game saved"

#: core/commands/stats.py:31 tests/core/commands/testStats.py:15
msgid "STAT_CURRENT_HP"
msgstr "Health"

#: core/commands/stats.py:32 tests/core/commands/testStats.py:16
msgid "STAT_ATTACK"
msgstr "Attack"

#: core/commands/stats.py:33 tests/core/commands/testStats.py:17
msgid "STAT_DEFENCE"
msgstr "Defence"

#: core/commands/stats.py:34 tests/core/commands/testStats.py:19
msgid "STAT_SPEED"
msgstr "Speed"

#: core/commands/stats.py:35 tests/core/commands/testStats.py:18
msgid "STAT_LUCK"
msgstr "Luck"

#: core/commands/take.py:15 tests/core/commands/testTake.py:45
#: tests/core/commands/testTake.py:50 tests/core/commands/testTake.py:55
#: tests/core/commands/testTake.py:60
msgid "ERROR_TAKE_NO_ITEM_GIVEN"
msgstr "What shall I take?"

#: core/commands/take.py:17 tests/core/commands/testTake.py:24
#: tests/core/commands/testTake.py:29
msgid "ERROR_TAKE_TOO_LOW_QUANTITY"
msgstr "You must take at least one item."

#: core/commands/take.py:19 tests/core/commands/testTake.py:14
#: tests/core/commands/testTake.py:19
msgid "ERROR_TAKE_INVALID_FORMAT_QUANTITY"
msgstr "The quantity of items to take must be a natural number."

#: core/commands/take.py:21 tests/core/commands/testTake.py:117
#: tests/core/commands/testTake.py:122
msgid "ERROR_TAKE_INVALID_CONTAINER_INDEX"
msgstr "The provided container index is not valid. Natural number expected."

#: core/commands/take.py:27 tests/core/commands/testTake.py:65
#: tests/core/commands/testTake.py:70
msgid "ERROR_TAKE_UNKNOWN_ITEM"
msgstr "I don't see this here."

#: core/commands/take.py:43 tests/core/commands/testTake.py:75
#: tests/core/commands/testTake.py:80
msgid "ERROR_TAKE_ITEM_NOT_AVAILABLE"
msgstr "I don't see this here."

#: core/commands/take.py:46 tests/core/commands/testTake.py:34
#: tests/core/commands/testTake.py:39
#, python-format
msgid "ERROR_TAKE_QUANTITY_TOO_HIGH_%s"
msgstr "You can't take that many %s"

#: core/commands/take.py:59 tests/core/commands/testTake.py:146
#: tests/core/commands/testTake.py:160 tests/core/commands/testTake.py:170
#: tests/core/commands/testTake.py:180 tests/core/commands/testTake.py:190
#: tests/core/commands/testTake.py:200
#, python-format
msgid "TAKE_CONFIRMATION_%(quantity)s_%(name)s"
msgstr "You take %(quantity)s %(name)s"

#: core/commands/talk.py:18 tests/core/commands/testTalk.py:13
#: tests/core/commands/testTalk.py:18
msgid "ERROR_TALK_NO_CHARACTER_GIVEN"
msgstr "Who must I talk to?"

#: core/commands/talk.py:20 tests/core/commands/testTalk.py:23
#: tests/core/commands/testTalk.py:28
msgid "ERROR_TALK_NO_SENTENCE_GIVEN"
msgstr "What must I say?"

#: core/commands/talk.py:29 tests/core/commands/testTalk.py:33
#: tests/core/commands/testTalk.py:38
msgid "ERROR_TALK_UNKNOWN_CHARACTER"
msgstr "Unknow character"

#: core/commands/talk.py:36 tests/core/commands/testTalk.py:43
msgid "ERROR_TALK_UNKNOWN_SENTENCE"
msgstr "What?"

#: models/area.py:21
msgid "DIRECTION_KEY_NORTH"
msgstr "north"

#: models/area.py:22 tests/core/commands/testAttack.py:27
#: tests/core/commands/testLook.py:147 tests/core/commands/testLook.py:156
#: tests/core/commands/testMove.py:31 tests/core/commands/testMove.py:36
#: tests/core/commands/testMove.py:43 tests/core/commands/testMove.py:45
#: tests/core/commands/testMove.py:51 tests/core/commands/testMove.py:53
#: tests/core/commands/testMove.py:58 tests/core/commands/testMove.py:68
#: tests/core/commands/testMove.py:79 tests/core/commands/testMove.py:89
msgid "DIRECTION_KEY_EAST"
msgstr "east"

#: models/area.py:23 tests/core/commands/testAttack.py:25
#: tests/core/commands/testAttack.py:31 tests/core/commands/testEnter.py:21
#: tests/core/commands/testEnter.py:28 tests/core/commands/testLook.py:21
#: tests/core/commands/testLook.py:40 tests/core/commands/testLook.py:92
#: tests/core/commands/testLook.py:98 tests/core/commands/testLook.py:145
#: tests/core/commands/testLook.py:154 tests/core/commands/testLook.py:163
#: tests/core/commands/testLook.py:165 tests/core/commands/testMove.py:41
#: tests/core/commands/testMove.py:49 tests/core/commands/testMove.py:56
#: tests/core/commands/testMove.py:66 tests/core/commands/testMove.py:75
#: tests/core/commands/testMove.py:85 tests/core/commands/testMove.py:94
#: tests/core/commands/testMove.py:96 tests/core/commands/testMove.py:99
#: tests/core/commands/testMove.py:101 tests/core/commands/testSave.py:186
#: tests/core/commands/testSave.py:196 tests/core/commands/testSave.py:208
#: tests/core/commands/testSave.py:210
msgid "DIRECTION_KEY_SOUTH"
msgstr "south"

#: models/area.py:24 tests/core/commands/testAttack.py:33
#: tests/core/commands/testMove.py:60 tests/core/commands/testMove.py:62
#: tests/core/commands/testMove.py:70 tests/core/commands/testMove.py:72
#: tests/core/commands/testMove.py:77 tests/core/commands/testMove.py:81
#: tests/core/commands/testMove.py:87
msgid "DIRECTION_KEY_WEST"
msgstr "west"

#: models/area.py:39
msgid "AREA_TYPE_DUNGEON"
msgstr "dungeon"

#: models/area.py:39
msgid "AREA_TYPE_LAND"
msgstr "land"

#: models/item_container.py:43 tests/core/commands/testDrop.py:118
#: tests/core/commands/testDrop.py:125 tests/core/commands/testOpen.py:33
#: tests/core/commands/testOpen.py:38 tests/core/commands/testTake.py:86
#: tests/core/commands/testTake.py:91
msgid "ERROR_UNKNOWN_ITEM_CONTAINER_TYPE_LABEL"
msgstr "This container type does not exist"

#: models/place.py:15 models/place.py:29 models/place.py:39 models/place.py:46
#: tests/core/commands/testEnter.py:23 tests/core/commands/testEnter.py:69
#: tests/core/commands/testEnter.py:74 tests/core/commands/testExit.py:20
#: tests/core/commands/testExit.py:25
msgid "PLACE_TYPE_CAVE"
msgstr "cave"

#: models/place.py:15 models/place.py:27 models/place.py:37 models/place.py:44
#: tests/core/commands/testEnter.py:45 tests/core/commands/testEnter.py:47
#: tests/core/commands/testEnter.py:52 tests/core/commands/testEnter.py:54
#: tests/core/commands/testEnter.py:59 tests/core/commands/testEnter.py:64
#: tests/core/commands/testExit.py:40 tests/core/commands/testExit.py:45
#: tests/core/commands/testExit.py:50 tests/core/commands/testExit.py:52
#: tests/core/commands/testExit.py:57 tests/core/commands/testExit.py:59
msgid "PLACE_TYPE_DUNGEON"
msgstr "dungeon"

#: models/place.py:25 models/place.py:35 tests/core/commands/testEnter.py:37
#: tests/core/commands/testEnter.py:42 tests/core/commands/testExit.py:32
#: tests/core/commands/testExit.py:37
msgid "ERROR_UNKNOWN_PLACE_TYPE"
msgstr "Unknown place type"

#: models/place.py:93
msgid "ERROR_PLACE_GENERATION"
msgstr "An error occured during the place loading"

#: models/player.py:26 tests/core/commands/testAuthenticate.py:25
#: tests/core/commands/testAuthenticate.py:30
msgid "ERROR_CONNECT_INVALID_CREDENTIALS"
msgstr "Invalid login"
