# English translations for PACKAGE package.
# Copyright (C) 2014 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Automatically generated, 2014.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-03-14 08:08+0000\n"
"PO-Revision-Date: 2014-03-07 22:38+0000\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"Language: en_GB\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ASCII\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: core/Rpg.py:52
msgid "ERROR_UNKNOWN_SELECTED_WORLD"
msgstr "Unknown selected world"

#: core/Rpg.py:60
msgid "ERROR_NO_SELECTED_PLAYER"
msgstr "A player is required"

#: core/Rpg.py:84
msgid "PLAYER_SELECTION"
msgstr "Player selection"

#: core/Rpg.py:85
msgid "CHOICE_NEW_PLAYER"
msgstr "Create a new player"

#: core/Rpg.py:86
msgid "CHOICE_EXISTING_PLAYER"
msgstr "Choose an existing player"

#: core/Rpg.py:89
msgid "CHOICE_QUESTION"
msgstr "Your choice? "

#: core/Rpg.py:109 core/commands/createPlayer.py:45
msgid "LOGIN_PROMPT"
msgstr "Login: "

#: core/Rpg.py:221
msgid "COMMAND_PROMPT"
msgstr "Command: "

#: core/command_factory.py:43 core/commands/help.py:38
#: tests/commands/testHelp.py:26 tests/commands/testHelp.py:75
#: tests/commands/testLook.py:15 tests/commands/testLook.py:40
#: tests/commands/testLook.py:52 tests/commands/testLook.py:57
#: tests/commands/testLook.py:63 tests/commands/testLook.py:68
#: tests/commands/testLook.py:73 tests/commands/testLook.py:78
#: tests/commands/testLook.py:83 tests/commands/testLook.py:91
#: tests/commands/testLook.py:96 tests/commands/testLook.py:101
#: tests/commands/testLook.py:106 tests/commands/testLook.py:112
#: tests/commands/testLook.py:117 tests/commands/testLook.py:125
msgid "LOOK_COMMAND"
msgstr "look"

#: core/command_factory.py:44 core/commands/help.py:22
#: tests/commands/testHelp.py:18 tests/commands/testHelp.py:59
#: tests/commands/testTalk.py:14 tests/commands/testTalk.py:19
#: tests/commands/testTalk.py:24 tests/commands/testTalk.py:29
#: tests/commands/testTalk.py:34 tests/commands/testTalk.py:39
#: tests/commands/testTalk.py:44 tests/commands/testTalk.py:49
#: tests/commands/testTalk.py:54
msgid "TALK_COMMAND"
msgstr "talk"

#: core/command_factory.py:45 core/commands/help.py:26
#: tests/commands/testEnter.py:24 tests/commands/testEnter.py:31
#: tests/commands/testHelp.py:20 tests/commands/testHelp.py:63
#: tests/commands/testMove.py:14 tests/commands/testMove.py:19
#: tests/commands/testMove.py:24 tests/commands/testMove.py:29
#: tests/commands/testMove.py:34 tests/commands/testMove.py:39
#: tests/commands/testMove.py:44 tests/commands/testMove.py:46
#: tests/commands/testMove.py:52 tests/commands/testMove.py:54
#: tests/commands/testMove.py:59 tests/commands/testMove.py:64
msgid "MOVE_COMMAND"
msgstr "move"

#: core/command_factory.py:46 core/commands/help.py:30
#: tests/commands/testEnter.py:14 tests/commands/testEnter.py:19
#: tests/commands/testEnter.py:26 tests/commands/testEnter.py:33
#: tests/commands/testEnter.py:38 tests/commands/testEnter.py:43
#: tests/commands/testEnter.py:48 tests/commands/testEnter.py:50
#: tests/commands/testEnter.py:55 tests/commands/testEnter.py:57
#: tests/commands/testEnter.py:62 tests/commands/testEnter.py:67
#: tests/commands/testEnter.py:72 tests/commands/testEnter.py:77
#: tests/commands/testExit.py:53 tests/commands/testExit.py:60
#: tests/commands/testHelp.py:22 tests/commands/testHelp.py:67
msgid "ENTER_COMMAND"
msgstr "enter"

#: core/command_factory.py:47 core/commands/help.py:34
#: tests/commands/testExit.py:13 tests/commands/testExit.py:18
#: tests/commands/testExit.py:23 tests/commands/testExit.py:28
#: tests/commands/testExit.py:33 tests/commands/testExit.py:38
#: tests/commands/testExit.py:43 tests/commands/testExit.py:48
#: tests/commands/testExit.py:55 tests/commands/testExit.py:62
#: tests/commands/testHelp.py:24 tests/commands/testHelp.py:71
msgid "EXIT_COMMAND"
msgstr "exit"

#: core/command_factory.py:48 core/commands/help.py:51
#: tests/commands/testDrop.py:51 tests/commands/testDrop.py:63
#: tests/commands/testDrop.py:117 tests/commands/testDrop.py:124
#: tests/commands/testDrop.py:131 tests/commands/testDrop.py:138
#: tests/commands/testDrop.py:146 tests/commands/testDrop.py:153
#: tests/commands/testDrop.py:160 tests/commands/testDrop.py:167
#: tests/commands/testDrop.py:174 tests/commands/testDrop.py:184
#: tests/commands/testDrop.py:195 tests/commands/testDrop.py:202
#: tests/commands/testDrop.py:209 tests/commands/testDrop.py:216
#: tests/commands/testDrop.py:223 tests/commands/testDrop.py:230
#: tests/commands/testDrop.py:237 tests/commands/testDrop.py:244
#: tests/commands/testDrop.py:251 tests/commands/testDrop.py:258
#: tests/commands/testDrop.py:265 tests/commands/testDrop.py:272
#: tests/commands/testHelp.py:33 tests/commands/testHelp.py:87
#: tests/commands/testInventory.py:24 tests/commands/testInventory.py:32
#: tests/commands/testTake.py:15 tests/commands/testTake.py:20
#: tests/commands/testTake.py:25 tests/commands/testTake.py:30
#: tests/commands/testTake.py:35 tests/commands/testTake.py:40
#: tests/commands/testTake.py:46 tests/commands/testTake.py:51
#: tests/commands/testTake.py:56 tests/commands/testTake.py:61
#: tests/commands/testTake.py:66 tests/commands/testTake.py:71
#: tests/commands/testTake.py:76 tests/commands/testTake.py:81
#: tests/commands/testTake.py:87 tests/commands/testTake.py:92
#: tests/commands/testTake.py:97 tests/commands/testTake.py:102
#: tests/commands/testTake.py:108 tests/commands/testTake.py:113
#: tests/commands/testTake.py:118 tests/commands/testTake.py:123
#: tests/commands/testTake.py:128 tests/commands/testTake.py:131
#: tests/commands/testTake.py:136 tests/commands/testTake.py:138
#: tests/commands/testTake.py:141 tests/commands/testTake.py:147
#: tests/commands/testTake.py:152 tests/commands/testTake.py:157
#: tests/commands/testTake.py:162 tests/commands/testTake.py:167
#: tests/commands/testTake.py:172 tests/commands/testTake.py:177
#: tests/commands/testTake.py:182 tests/commands/testTake.py:187
#: tests/commands/testTake.py:192 tests/commands/testTake.py:197
#: tests/commands/testTake.py:202
msgid "TAKE_COMMAND"
msgstr "take"

#: core/command_factory.py:49 core/commands/help.py:61
#: tests/commands/testDrop.py:17 tests/commands/testDrop.py:26
#: tests/commands/testDrop.py:35 tests/commands/testDrop.py:44
#: tests/commands/testDrop.py:56 tests/commands/testDrop.py:68
#: tests/commands/testDrop.py:76 tests/commands/testDrop.py:81
#: tests/commands/testDrop.py:86 tests/commands/testDrop.py:91
#: tests/commands/testDrop.py:96 tests/commands/testDrop.py:101
#: tests/commands/testDrop.py:106 tests/commands/testDrop.py:111
#: tests/commands/testDrop.py:119 tests/commands/testDrop.py:126
#: tests/commands/testDrop.py:133 tests/commands/testDrop.py:140
#: tests/commands/testDrop.py:148 tests/commands/testDrop.py:155
#: tests/commands/testDrop.py:162 tests/commands/testDrop.py:169
#: tests/commands/testDrop.py:176 tests/commands/testDrop.py:179
#: tests/commands/testDrop.py:186 tests/commands/testDrop.py:189
#: tests/commands/testDrop.py:197 tests/commands/testDrop.py:204
#: tests/commands/testDrop.py:211 tests/commands/testDrop.py:218
#: tests/commands/testDrop.py:225 tests/commands/testDrop.py:232
#: tests/commands/testDrop.py:239 tests/commands/testDrop.py:246
#: tests/commands/testDrop.py:253 tests/commands/testDrop.py:260
#: tests/commands/testDrop.py:267 tests/commands/testDrop.py:274
#: tests/commands/testHelp.py:41 tests/commands/testHelp.py:91
msgid "DROP_COMMAND"
msgstr "drop"

#: core/command_factory.py:50 core/commands/help.py:42
#: tests/commands/testHelp.py:28 tests/commands/testHelp.py:79
#: tests/commands/testInventory.py:14 tests/commands/testInventory.py:19
#: tests/commands/testInventory.py:26 tests/commands/testInventory.py:34
msgid "INVENTORY_COMMAND"
msgstr "inventory"

#: core/command_factory.py:51 core/commands/help.py:42
#: tests/commands/testHelp.py:28 tests/commands/testHelp.py:79
msgid "INVENTORY_SHORT_COMMAND"
msgstr "inv"

#: core/command_factory.py:52 tests/commands/testStats.py:15
#: tests/commands/testStats.py:38
msgid "STATS_COMMAND"
msgstr "stats"

#: core/command_factory.py:53 core/commands/help.py:70
#: tests/commands/testHelp.py:15 tests/commands/testHelp.py:48
#: tests/commands/testHelp.py:55 tests/commands/testHelp.py:95
msgid "HELP_COMMAND"
msgstr "help"

#: core/command_factory.py:54 core/commands/help.py:46
#: tests/commands/testHelp.py:30 tests/commands/testHelp.py:83
#: tests/commands/testOpen.py:14 tests/commands/testOpen.py:19
#: tests/commands/testOpen.py:24 tests/commands/testOpen.py:29
#: tests/commands/testOpen.py:34 tests/commands/testOpen.py:39
#: tests/commands/testOpen.py:44 tests/commands/testOpen.py:49
#: tests/commands/testOpen.py:54 tests/commands/testOpen.py:63
#: tests/commands/testOpen.py:68 tests/commands/testOpen.py:72
#: tests/commands/testOpen.py:80 tests/commands/testOpen.py:84
#: tests/commands/testOpen.py:92 tests/commands/testOpen.py:101
#: tests/commands/testOpen.py:105 tests/commands/testOpen.py:109
#: tests/commands/testOpen.py:113 tests/commands/testOpen.py:117
msgid "OPEN_COMMAND"
msgstr "open"

#: core/command_factory.py:55
msgid "ATTACK_COMMAND"
msgstr "attack"

#: core/command_factory.py:82 core/commands/help.py:74
#: tests/commands/testHelp.py:50 tests/commands/testHelp.py:99
msgid "QUIT_COMMAND"
msgstr "quit"

#: core/command_factory.py:82 core/commands/help.py:74
#: tests/commands/testHelp.py:50 tests/commands/testHelp.py:99
msgid "QUIT_SHORT_COMMAND"
msgstr "q"

#: core/command_factory.py:89
msgid "ERROR_DENIED_COMMAND_WHILE_FIGHTING"
msgstr "You can't use this command while fighting"

#: core/command_factory.py:96 core/command_factory.py:109
msgid "ERROR_UNKNOWN_COMMAND"
msgstr "Unknown command"

#: core/commands/attack.py:19
msgid "ERROR_FIGHT_NOT_FIGHTING"
msgstr "You are not fighting"

#: core/commands/attack.py:29
#, python-brace-format
msgid "ATTACK_CONFIRM_PLAYER_TO_ENEMY_{enemy}_{damages}"
msgstr "You attack the {enemy} and deal {damages} damage points"

#: core/commands/attack.py:30 core/commands/move.py:74
#, python-brace-format
msgid "ATTACK_CONFIRM_ENEMY_TO_PLAYER_{enemy}_{damages}"
msgstr "The {enemy} attacks you reducing your health of {damages} points"

#: core/commands/attack.py:31
#, python-brace-format
msgid "ATTACK_VICTORY_{enemy}"
msgstr "You slay the {enemy}"

#: core/commands/attack.py:32
#, python-brace-format
msgid "ATTACK_LOST_{enemy}"
msgstr "The {enemy} achieves you"

#: core/commands/authenticate.py:17 tests/commands/testAuthenticate.py:18
#: tests/commands/testAuthenticate.py:23
msgid "ERROR_AUTHENTICATE_ARGUMENTS_NUMBER"
msgstr "One argument is required (Login)"

#: core/commands/authenticate.py:26 tests/commands/testAuthenticate.py:38
msgid "PLAYER_AUTHENTICATION_CONFIRMATION"
msgstr "Player connected"

#: core/commands/createPlayer.py:23 tests/commands/testCreatePlayer.py:18
#: tests/commands/testCreatePlayer.py:23
msgid "ERROR_SIGNUP_NOT_ENOUGH_ARGUMENTS"
msgstr "More arguments are required to create a player"

#: core/commands/createPlayer.py:28 core/commands/createPlayer.py:48
#: tests/commands/testCreatePlayer.py:28 tests/commands/testCreatePlayer.py:33
msgid "ERROR_SIGNUP_LOGIN_ALREADY_USED"
msgstr "This login is already used"

#: core/commands/createPlayer.py:32 tests/commands/testCreatePlayer.py:38
#: tests/commands/testCreatePlayer.py:43
msgid "ERROR_SIGNUP_INVALID_GENDER"
msgstr "Invalid gender"

#: core/commands/createPlayer.py:36 tests/commands/testCreatePlayer.py:48
#: tests/commands/testCreatePlayer.py:53
msgid "ERROR_SIGNUP_INVALID_SPECIES"
msgstr "Invalid species"

#: core/commands/createPlayer.py:54
msgid "GENDER_SELECTION"
msgstr "Gender selection"

#: core/commands/createPlayer.py:60
msgid "GENDER_PROMPT"
msgstr "Gender: "

#: core/commands/createPlayer.py:74
msgid "SPECIES_SELECTION"
msgstr "Species selection"

#: core/commands/createPlayer.py:81
msgid "SPECIES_PROMPT"
msgstr "Species: "

#: core/commands/createPlayer.py:94 tests/commands/testCreatePlayer.py:58
msgid "PLAYER_CREATION_CONFIRMATION"
msgstr "Player created"

#: core/commands/drop.py:20 tests/commands/testDrop.py:78
#: tests/commands/testDrop.py:83 tests/commands/testDrop.py:88
#: tests/commands/testDrop.py:93
msgid "ERROR_DROP_NO_ITEM_GIVEN"
msgstr "What shall I drop?"

#: core/commands/drop.py:22 tests/commands/testDrop.py:37
#: tests/commands/testDrop.py:46
msgid "ERROR_DROP_TOO_LOW_QUANTITY"
msgstr "You must drop at least one item."

#: core/commands/drop.py:24 tests/commands/testDrop.py:19
#: tests/commands/testDrop.py:28
msgid "ERROR_DROP_INVALID_FORMAT_QUANTITY"
msgstr "The quantity of items to drop must be a natural number."

#: core/commands/drop.py:26 tests/commands/testDrop.py:164
#: tests/commands/testDrop.py:171
msgid "ERROR_DROP_INVALID_CONTAINER_INDEX"
msgstr "The provided container index is not valid. Natural number expected."

#: core/commands/drop.py:40 tests/commands/testDrop.py:98
#: tests/commands/testDrop.py:103
msgid "ERROR_DROP_UNKNOWN_ITEM"
msgstr "I have none of those"

#: core/commands/drop.py:45 tests/commands/testDrop.py:108
#: tests/commands/testDrop.py:113
msgid "ERROR_DROP_ITEM_NOT_AVAILABLE"
msgstr "I have none of those"

#: core/commands/drop.py:47 tests/commands/testDrop.py:58
#: tests/commands/testDrop.py:70
#, python-format
msgid "ERROR_DROP_QUANTITY_TOO_HIGH_%s"
msgstr "I don't have enough %s to drop"

#: core/commands/drop.py:62 tests/commands/testDrop.py:199
#: tests/commands/testDrop.py:213 tests/commands/testDrop.py:227
#: tests/commands/testDrop.py:241 tests/commands/testDrop.py:255
#: tests/commands/testDrop.py:269
#, python-format
msgid "DROP_CONFIRMATION_%(quantity)s_%(name)s"
msgstr "You drop %(quantity)s %(name)s"

#: core/commands/enter.py:21 tests/commands/testEnter.py:16
#: tests/commands/testEnter.py:21
msgid "ERROR_ENTER_NO_PLACE_GIVEN"
msgstr "I can't enter into nothing"

#: core/commands/enter.py:27 core/commands/exit.py:27
#: tests/commands/testEnter.py:28 tests/commands/testEnter.py:35
#: tests/commands/testEnter.py:52 tests/commands/testEnter.py:59
#: tests/commands/testExit.py:25 tests/commands/testExit.py:30
#: tests/commands/testExit.py:45 tests/commands/testExit.py:50
msgid "ERROR_ENTER_PLACE_NOT_AVAILABLE"
msgstr "There is no such place here"

#: core/commands/enter.py:32 tests/commands/testEnter.py:64
#: tests/commands/testEnter.py:69 tests/commands/testEnter.py:74
#: tests/commands/testEnter.py:79
msgid "ENTER_CONFIRMATION"
msgstr "You enter."

#: core/commands/exit.py:21 tests/commands/testExit.py:15
#: tests/commands/testExit.py:20
msgid "ERROR_EXIT_NO_PLACE_GIVEN"
msgstr "I can't exit out of nothing"

#: core/commands/exit.py:30 tests/commands/testExit.py:57
#: tests/commands/testExit.py:64
msgid "EXIT_CONFIRMATION"
msgstr "You are now outside"

#: core/commands/help.py:22 tests/commands/testHelp.py:18
#: tests/commands/testHelp.py:59
msgid "CHARACTER_TOKEN"
msgstr "character name"

#: core/commands/help.py:22 tests/commands/testHelp.py:18
#: tests/commands/testHelp.py:59
msgid "SENTENCE_TOKEN"
msgstr "sentence"

#: core/commands/help.py:23 tests/commands/testHelp.py:19
#: tests/commands/testHelp.py:60
msgid "TALK_COMMAND_DESCRIPTION"
msgstr "Talk to a character"

#: core/commands/help.py:27 tests/commands/testHelp.py:21
#: tests/commands/testHelp.py:64
msgid "MOVE_COMMAND_DESCRIPTION"
msgstr "Go to the indicated direction"

#: core/commands/help.py:31 tests/commands/testHelp.py:23
#: tests/commands/testHelp.py:68
msgid "ENTER_COMMAND_DESCRIPTION"
msgstr ""
"Enter in the selected place (if the place is available in the current cell)"

#: core/commands/help.py:35 tests/commands/testHelp.py:25
#: tests/commands/testHelp.py:72
msgid "EXIT_COMMAND_DESCRIPTION"
msgstr "Exit from the selected place (if the current cell is the place exit)"

#: core/commands/help.py:39 tests/commands/testHelp.py:27
#: tests/commands/testHelp.py:76
msgid "LOOK_COMMAND_DESCRIPTION"
msgstr ""
"List everything which is in the current area (characters, items, neighbour "
"areas...)"

#: core/commands/help.py:43 tests/commands/testHelp.py:29
#: tests/commands/testHelp.py:80
msgid "INVENTORY_COMMAND_DESCRIPTION"
msgstr "List the items the player has in his inventory"

#: core/commands/help.py:46 core/commands/help.py:55 core/commands/help.py:65
#: tests/commands/testHelp.py:30 tests/commands/testHelp.py:37
#: tests/commands/testHelp.py:45 tests/commands/testHelp.py:83
#: tests/commands/testHelp.py:87 tests/commands/testHelp.py:91
msgid "CONTAINER_INDEX_TOKEN"
msgstr "container index"

#: core/commands/help.py:46 core/commands/help.py:54 core/commands/help.py:64
#: tests/commands/testHelp.py:30 tests/commands/testHelp.py:36
#: tests/commands/testHelp.py:44 tests/commands/testHelp.py:83
#: tests/commands/testHelp.py:87 tests/commands/testHelp.py:91
msgid "CONTAINER_TOKEN"
msgstr "container"

#: core/commands/help.py:47 tests/commands/testHelp.py:31
#: tests/commands/testHelp.py:84
msgid "OPEN_COMMAND_DESCRIPTION"
msgstr "List the items available in a given container"

#: core/commands/help.py:52 core/commands/help.py:62
#: tests/commands/testHelp.py:34 tests/commands/testHelp.py:42
#: tests/commands/testHelp.py:87 tests/commands/testHelp.py:91
msgid "QUANTITY_TOKEN"
msgstr "quantity"

#: core/commands/help.py:53 core/commands/help.py:63
#: tests/commands/testHelp.py:35 tests/commands/testHelp.py:43
#: tests/commands/testHelp.py:87 tests/commands/testHelp.py:91
msgid "ITEM_NAME_TOKEN"
msgstr "item name"

#: core/commands/help.py:57 tests/commands/testHelp.py:39
#: tests/commands/testHelp.py:88
msgid "TAKE_COMMAND_DESCRIPTION"
msgstr "Take some items on the ground"

#: core/commands/help.py:67 tests/commands/testHelp.py:47
#: tests/commands/testHelp.py:92
msgid "DROP_COMMAND_DESCRIPTION"
msgstr "Drop some items from your inventory"

#: core/commands/help.py:71 tests/commands/testHelp.py:49
#: tests/commands/testHelp.py:96
msgid "HELP_COMMAND_DESCRIPTION"
msgstr "Display the help menu"

#: core/commands/help.py:75 tests/commands/testHelp.py:51
#: tests/commands/testHelp.py:100
msgid "QUIT_COMMAND_DESCRIPTION"
msgstr "Quit the game"

#: core/commands/help.py:80 tests/commands/testHelp.py:17
msgid "AVAILABLE_COMMANDS_TITLE"
msgstr "Available commands"

#: core/commands/inventory.py:27 tests/commands/testInventory.py:16
msgid "INVENTORY_EMPTY"
msgstr "Your inventory is empty"

#: core/commands/item_interaction.py:50 tests/commands/testDrop.py:135
#: tests/commands/testDrop.py:142 tests/commands/testOpen.py:26
#: tests/commands/testOpen.py:31 tests/commands/testTake.py:99
#: tests/commands/testTake.py:104
msgid "ERROR_CONTAINER_NOT_AVAILABLE"
msgstr "There is no container with this type here"

#: core/commands/item_interaction.py:56 tests/commands/testDrop.py:178
#: tests/commands/testDrop.py:181 tests/commands/testDrop.py:188
#: tests/commands/testDrop.py:191 tests/commands/testOpen.py:70
#: tests/commands/testOpen.py:82 tests/commands/testOpen.py:103
#: tests/commands/testOpen.py:111 tests/commands/testTake.py:130
#: tests/commands/testTake.py:133 tests/commands/testTake.py:140
#: tests/commands/testTake.py:143
#, python-format
msgid "ERROR_OUT_OF_RANGE_ITEM_CONTAINER_INDEX_%d"
msgstr ""
"The provided container index is not valid. A natural number between 1 and %d "
"is expected."

#: core/commands/item_interaction.py:59 tests/commands/testDrop.py:150
#: tests/commands/testDrop.py:157 tests/commands/testOpen.py:46
#: tests/commands/testOpen.py:51 tests/commands/testTake.py:110
#: tests/commands/testTake.py:115
msgid "ERROR_MULTIPLE_CONTAINERS_AVAILABLE"
msgstr ""
"There are more than one container with this type here, an explicit index is "
"required"

#: core/commands/look.py:20 tests/commands/testLook.py:63
#: tests/commands/testLook.py:68
msgid "LOOK_REGION_PARAM"
msgstr "region"

#: core/commands/look.py:21
msgid "LOOK_FIGHT_PARAM"
msgstr "enemies"

#: core/commands/look.py:22 tests/commands/testLook.py:73
#: tests/commands/testLook.py:78
msgid "LOOK_CHARACTERS_PARAM"
msgstr "characters"

#: core/commands/look.py:23 tests/commands/testLook.py:83
#: tests/commands/testLook.py:91
msgid "LOOK_DIRECTIONS_PARAM"
msgstr "diections"

#: core/commands/look.py:24 tests/commands/testLook.py:96
#: tests/commands/testLook.py:101
msgid "LOOK_PLACES_PARAM"
msgstr "places"

#: core/commands/look.py:25 tests/commands/testLook.py:106
#: tests/commands/testLook.py:112
msgid "LOOK_OBJECTS_PARAM"
msgstr "objects"

#: core/commands/look.py:26 tests/commands/testLook.py:117
#: tests/commands/testLook.py:125
msgid "LOOK_CONTAINERS_PARAM"
msgstr "containers"

#: core/commands/look.py:38 tests/commands/testLook.py:54
#: tests/commands/testLook.py:59
msgid "ERROR_LOOK_UNKNOWN_SECTION"
msgstr "Unknown option for the look command"

#: core/commands/look.py:102 tests/commands/testLook.py:18
#: tests/commands/testLook.py:65
#, python-format
msgid "CURRENT_REGION_%s"
msgstr "You are in %s"

#: core/commands/look.py:105
#, python-format
msgid "CURRENTLY_FIGHTING_%s"
msgstr "You are currently fighting: %s"

#: core/commands/look.py:109 tests/commands/testLook.py:20
#: tests/commands/testLook.py:75
msgid "PRESENT_CHARACTERS"
msgstr "You see these characters arround:"

#: core/commands/look.py:116 tests/commands/testLook.py:23
#: tests/commands/testLook.py:86
msgid "AVAILABLE_DIRECTIONS"
msgstr "You can go in the following directions:"

#: core/commands/look.py:123 tests/commands/testLook.py:26
#: tests/commands/testLook.py:98
msgid "AVAILABLE_PLACES"
msgstr "You see the following places:"

#: core/commands/look.py:130 tests/commands/testLook.py:30
#: tests/commands/testLook.py:108
msgid "AVAILABLE_ITEMS"
msgstr "You see the following items"

#: core/commands/look.py:137 tests/commands/testLook.py:33
#: tests/commands/testLook.py:119
msgid "AVAILABLE_ITEMS_CONTAINERS"
msgstr "Available containers"

#: core/commands/move.py:21 tests/commands/testMove.py:16
#: tests/commands/testMove.py:21
msgid "ERROR_MOVE_NO_DIRECTION_GIVEN"
msgstr "Where shall I go?"

#: core/commands/move.py:25 tests/commands/testMove.py:26
#: tests/commands/testMove.py:31
#, python-format
msgid "ERROR_MOVE_INVALID_DIRECTION_%s"
msgstr "%s is not a valid direction"

#: core/commands/move.py:34 tests/commands/testMove.py:36
#: tests/commands/testMove.py:41
msgid "ERROR_MOVE_DIRECTION_NOT_AVAILABLE"
msgstr "I can't go there"

#: core/commands/move.py:41
msgid "ERROR_FLEE_FIGHT_FAILS"
msgstr "You can't run away from this fight"

#: core/commands/move.py:71
#, python-brace-format
msgid "MOVE_CONFIRMATION_{direction}_FIGHT_FLEE_{enemy}"
msgstr "You manage to escape the {enemy} and head towards {direction}"

#: core/commands/move.py:72 tests/commands/testMove.py:49
#, python-brace-format
msgid "MOVE_CONFIRMATION_{direction}_FIGHT_{enemy}"
msgstr "let's go {direction}. A {enemy} attacks you"

#: core/commands/move.py:73
#, python-brace-format
msgid "MOVE_CONFIRMATION_{direction}_AMBUSH_{enemy}"
msgstr "let's go {direction}. You are ambushed by a {enemy}"

#: core/commands/move.py:90 tests/commands/testMove.py:61
#, python-format
msgid "MOVE_CONFIRMATION_%s"
msgstr "let's go %s"

#: core/commands/open.py:18 tests/commands/testOpen.py:16
#: tests/commands/testOpen.py:21
msgid "ERROR_OPEN_NO_CONTAINER_PROVIDED"
msgstr "A container type must be provided"

#: core/commands/open.py:44 tests/commands/testOpen.py:57
#: tests/commands/testOpen.py:75 tests/commands/testOpen.py:87
#: tests/commands/testOpen.py:95
#, python-format
msgid "ITEMS_IN_CONTAINER_%s"
msgstr "Items in container %s"

#: core/commands/stats.py:31 tests/commands/testStats.py:18
msgid "STAT_CURRENT_HP"
msgstr "Health"

#: core/commands/stats.py:32 tests/commands/testStats.py:20
msgid "STAT_ATTACK"
msgstr "Attack"

#: core/commands/stats.py:33 tests/commands/testStats.py:19
msgid "STAT_DEFENCE"
msgstr "Defence"

#: core/commands/stats.py:34 tests/commands/testStats.py:21
msgid "STAT_SPEED"
msgstr "Speed"

#: core/commands/stats.py:35 tests/commands/testStats.py:22
msgid "STAT_LUCK"
msgstr "Luck"

#: core/commands/take.py:15 tests/commands/testTake.py:48
#: tests/commands/testTake.py:53 tests/commands/testTake.py:58
#: tests/commands/testTake.py:63
msgid "ERROR_TAKE_NO_ITEM_GIVEN"
msgstr "What shall I take?"

#: core/commands/take.py:17 tests/commands/testTake.py:27
#: tests/commands/testTake.py:32
msgid "ERROR_TAKE_TOO_LOW_QUANTITY"
msgstr "You must take at least one item."

#: core/commands/take.py:19 tests/commands/testTake.py:17
#: tests/commands/testTake.py:22
msgid "ERROR_TAKE_INVALID_FORMAT_QUANTITY"
msgstr "The quantity of items to take must be a natural number."

#: core/commands/take.py:21 tests/commands/testTake.py:120
#: tests/commands/testTake.py:125
msgid "ERROR_TAKE_INVALID_CONTAINER_INDEX"
msgstr "The provided container index is not valid. Natural number expected."

#: core/commands/take.py:27 tests/commands/testTake.py:68
#: tests/commands/testTake.py:73
msgid "ERROR_TAKE_UNKNOWN_ITEM"
msgstr "I don't see this here."

#: core/commands/take.py:43 tests/commands/testTake.py:78
#: tests/commands/testTake.py:83
msgid "ERROR_TAKE_ITEM_NOT_AVAILABLE"
msgstr "I don't see this here."

#: core/commands/take.py:46 tests/commands/testTake.py:37
#: tests/commands/testTake.py:42
#, python-format
msgid "ERROR_TAKE_QUANTITY_TOO_HIGH_%s"
msgstr "You can't take that many %s"

#: core/commands/take.py:59 tests/commands/testTake.py:149
#: tests/commands/testTake.py:159 tests/commands/testTake.py:169
#: tests/commands/testTake.py:179 tests/commands/testTake.py:189
#: tests/commands/testTake.py:199
#, python-format
msgid "TAKE_CONFIRMATION_%(quantity)s_%(name)s"
msgstr "You take %(quantity)s %(name)s"

#: core/commands/talk.py:18 tests/commands/testTalk.py:16
#: tests/commands/testTalk.py:21
msgid "ERROR_TALK_NO_CHARACTER_GIVEN"
msgstr "Who must I talk to?"

#: core/commands/talk.py:20 tests/commands/testTalk.py:26
#: tests/commands/testTalk.py:31
msgid "ERROR_TALK_NO_SENTENCE_GIVEN"
msgstr "What must I say?"

#: core/commands/talk.py:29 tests/commands/testTalk.py:36
#: tests/commands/testTalk.py:41
msgid "ERROR_TALK_UNKNOWN_CHARACTER"
msgstr "Unknow character"

#: core/commands/talk.py:36 tests/commands/testTalk.py:46
msgid "ERROR_TALK_UNKNOWN_SENTENCE"
msgstr "What?"

#: models/area.py:21
msgid "DIRECTION_KEY_NORTH"
msgstr "north"

#: models/area.py:22 tests/commands/testMove.py:34
#: tests/commands/testMove.py:39 tests/commands/testMove.py:46
#: tests/commands/testMove.py:48 tests/commands/testMove.py:54
#: tests/commands/testMove.py:56
msgid "DIRECTION_KEY_EAST"
msgstr "east"

#: models/area.py:23 tests/commands/testEnter.py:24
#: tests/commands/testEnter.py:31 tests/commands/testLook.py:24
#: tests/commands/testLook.py:43 tests/commands/testLook.py:87
#: tests/commands/testLook.py:93 tests/commands/testMove.py:44
#: tests/commands/testMove.py:52 tests/commands/testMove.py:59
#: tests/commands/testMove.py:61 tests/commands/testMove.py:64
#: tests/commands/testMove.py:66
msgid "DIRECTION_KEY_SOUTH"
msgstr "south"

#: models/area.py:24
msgid "DIRECTION_KEY_WEST"
msgstr "west"

#: models/area.py:39
msgid "AREA_TYPE_DUNGEON"
msgstr "dungeon"

#: models/area.py:39
msgid "AREA_TYPE_LAND"
msgstr "land"

#: models/item_container.py:32 tests/commands/testDrop.py:121
#: tests/commands/testDrop.py:128 tests/commands/testOpen.py:36
#: tests/commands/testOpen.py:41 tests/commands/testTake.py:89
#: tests/commands/testTake.py:94
msgid "ERROR_UNKNOWN_ITEM_CONTAINER_TYPE_LABEL"
msgstr "This container type does not exist"

#: models/place.py:15 models/place.py:29 models/place.py:39 models/place.py:46
#: tests/commands/testEnter.py:26 tests/commands/testEnter.py:72
#: tests/commands/testEnter.py:77 tests/commands/testExit.py:23
#: tests/commands/testExit.py:28
msgid "PLACE_TYPE_CAVE"
msgstr "cave"

#: models/place.py:15 models/place.py:27 models/place.py:37 models/place.py:44
#: tests/commands/testEnter.py:48 tests/commands/testEnter.py:50
#: tests/commands/testEnter.py:55 tests/commands/testEnter.py:57
#: tests/commands/testEnter.py:62 tests/commands/testEnter.py:67
#: tests/commands/testExit.py:43 tests/commands/testExit.py:48
#: tests/commands/testExit.py:53 tests/commands/testExit.py:55
#: tests/commands/testExit.py:60 tests/commands/testExit.py:62
msgid "PLACE_TYPE_DUNGEON"
msgstr "dungeon"

#: models/place.py:25 models/place.py:35 tests/commands/testEnter.py:40
#: tests/commands/testEnter.py:45 tests/commands/testExit.py:35
#: tests/commands/testExit.py:40
msgid "ERROR_UNKNOWN_PLACE_TYPE"
msgstr "Unknown place type"

#: models/place.py:93
msgid "ERROR_PLACE_GENERATION"
msgstr "An error occured during the place loading"

#: models/player.py:26 tests/commands/testAuthenticate.py:28
#: tests/commands/testAuthenticate.py:33
msgid "ERROR_CONNECT_INVALID_CREDENTIALS"
msgstr "Invalid login"
